package com.example.muscelton.hitech;

/**
 * Harjoitusten ydin lista
 * @author Elias Perttu
 */
public enum Exercise {
    KNEE_PUSH_UP,
    ELBOW_RAISE,
    SCAPULAR_PUSH,
    SQUAT,
    THREE_WAY_LUNGE,
    PLANK_OPPOSITE_KNEE_TO_ELBOW,
    JUMPING_JACKS,
    ISO_CRUNCHES,
    RECLINER_ELBOW_TO_KNEE_TUCKS,
    GLUTE_BRIDGE,
    PUSH_UP,
    //Keskitaso
    SPIDERMNA_PUSHUP,
    PIKE_PUSHUP,
    BEGINNER_SHRIMP,
    FLOOR_BRIDGE_HALF_ROTATION,
    SUPERMANS,
    STARFISH_CRUNCHES,
    WINDSHIELD_WIPERS,
    HEELS_TO_THE_HEAVENS,
    BURPEE,
    SPLIT_SQUAT_JUMPS,
    SQUAT_JUMPS,
    SINGLE_LEG_RDL,
    //Haastava
    BODYWEIGHT_SIDE_LATERAL_RAISES,
    DIAMOND_PUSHUP,
    PLYO_PUSHUP,
    ARCHER_PUSHUP,
    HINDU_PUSHUP,
    SQUAT_THRUST_X_PUSHUP,
    BRIDGE,
    COUSSAC_SQUAT,
    }
